// Generated by Axon v0.8.0 transpiler
// DO NOT EDIT — source: .axn


// ── Axon v0.4.0 stdlib ──────────────────────────────────────────────────────

/**
 * Apply fn to every element of xs and return the results.
 * @pure @total
 * @param {Array} xs
 * @param {Function} fn
 * @returns {Array}
 */
const map = (xs, fn) => xs.map(fn);

/**
 * Keep only elements of xs for which pred returns true.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {Array}
 */
const filter = (xs, pred) => xs.filter(pred);

/**
 * Reduce xs to a single value, starting from init.
 * @pure @total
 * @param {Array} xs
 * @param {*} init
 * @param {Function} fn
 * @returns {*}
 */
const fold = (xs, init, fn) => xs.reduce(fn, init);

/**
 * Apply a sequence of single-argument functions left to right.
 * @pure @total
 * @param {...Function} fns
 * @returns {Function}
 */
const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);

/**
 * Combine two arrays element-by-element into pairs.
 * @pure @total
 * @param {Array} xs
 * @param {Array} ys
 * @returns {Array}
 */
const zip = (xs, ys) => xs.map((x, i) => [x, ys[i]]);

/**
 * Produce an array of integers from start (inclusive) to end (exclusive).
 * @pure @total
 * @param {number} start
 * @param {number} end
 * @returns {number[]}
 */
const range = (start, end) => Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);

/**
 * Return the first element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const first = (xs) => xs[0];

/**
 * Return the last element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const last = (xs) => xs[xs.length - 1];

/**
 * Sum a numeric array.
 * @pure @total
 * @param {number[]} xs
 * @returns {number}
 */
const sum = (xs) => xs.reduce((a, b) => a + b, 0);

/**
 * Count elements matching pred, or total length if no pred given.
 * @pure @total
 * @param {Array} xs
 * @param {Function} [pred]
 * @returns {number}
 */
const count = (xs, pred) => pred ? xs.filter(pred).length : xs.length;

/**
 * True if any element satisfies pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const any = (xs, pred) => xs.some(pred);

/**
 * True if all elements satisfy pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const all = (xs, pred) => xs.every(pred);

/**
 * Flatten one level of nesting.
 * @pure @total
 * @param {Array} xs
 * @returns {Array}
 */
const flat = (xs) => xs.flat();

/**
 * Group an array into a Map by key function.
 * @pure @total
 * @param {Array} xs
 * @param {Function} keyFn
 * @returns {Map}
 */
const groupBy = (xs, keyFn) => xs.reduce((m, x) => {
  const k = keyFn(x);
  if (!m.has(k)) m.set(k, []);
  m.get(k).push(x);
  return m;
}, new Map());

/**
 * Return a new object with only the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const pick = (obj, keys) => Object.fromEntries(keys.filter(k => k in obj).map(k => [k, obj[k]]));

/**
 * Return a new object without the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k]) => !keys.includes(k)));

// ── Axon built-in constraint validators ─────────────────────────────────────
// Generated by 'type T = base where ...' declarations.

const __axon_presets = {
  email:   /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  url:     /^https?:\/\//,
  uuid:    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  alpha:   /^[a-zA-Z]+$/,
  alnum:   /^[a-zA-Z0-9]+$/,
  numeric: /^[0-9]+$/,
  slug:    /^[a-z0-9-]+$/,
  hex:     /^#?[0-9a-fA-F]{3,8}$/,
};

// ── Axon v0.6.0 Result type ──────────────────────────────────────────────────
// Result<T> = Ok { value: T } | Err { message: string }
// Constructors and helpers available in every Axon program.

/**
 * Wrap a value in Ok. Use as the success return of a @throws function.
 * @pure @total
 * @param {*} value
 * @returns {{ tag: 'Ok', value: * }}
 */
const ok = (value) => ({ tag: 'Ok', value });

/**
 * Wrap a message in Err. Use as the failure return of a @throws function.
 * @pure @total
 * @param {string} message
 * @returns {{ tag: 'Err', message: string }}
 */
const err = (message) => ({ tag: 'Err', message });

/**
 * True if result is Ok.
 * @pure @total
 * @param {{ tag: string }} r
 * @returns {boolean}
 */
const is_ok = (r) => r != null && r.tag === 'Ok';

/**
 * True if result is Err.
 * @pure @total
 * @param {{ tag: string }} r
 * @returns {boolean}
 */
const is_err = (r) => r != null && r.tag === 'Err';

/**
 * Unwrap Ok value — throws if Err.
 * @param {{ tag: string, value: *, message: string }} r
 * @returns {*}
 */
const unwrap = (r) => {
  if (r != null && r.tag === 'Ok') return r.value;
  throw new Error(r != null ? r.message : 'unwrap called on null');
};

/**
 * Unwrap Ok value, or return fallback if Err.
 * @pure @total
 * @param {{ tag: string, value: * }} r
 * @param {*} fallback
 * @returns {*}
 */
const unwrap_or = (r, fallback) => (r != null && r.tag === 'Ok') ? r.value : fallback;

// ── Axon v0.8.0 Async helpers ────────────────────────────────────────────────

/**
 * Return a Promise that resolves after ms milliseconds.
 * Use with await inside async fn declarations.
 * @param {number} ms  Duration in milliseconds
 * @returns {Promise<void>}
 */
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// ── Axon v0.4.0 test runner ──────────────────────────────────────────────────
// @test declarations push entries here. Call __runAxonTests() to execute them.
// Also exposed on globalThis so the CLI's vm context can access it.

const __axon_tests = [];

/**
 * Run all registered @test declarations. Returns a result summary.
 * @returns {{ passed: number, failed: number, total: number, results: Array }}
 */
const __runAxonTests = () => {
  let passed = 0, failed = 0;
  const results = [];
  for (const t of __axon_tests) {
    try {
      const ok = !!t.fn();
      if (ok) {
        passed++;
        results.push({ ok: true,  desc: t.desc });
      } else {
        failed++;
        results.push({ ok: false, desc: t.desc, error: 'assertion returned false' });
      }
    } catch(e) {
      failed++;
      results.push({ ok: false, desc: t.desc, error: String(e) });
    }
  }
  return { passed, failed, total: passed + failed, results };
};
// Expose on globalThis so the Node CLI vm context and browser window can both access it
if (typeof globalThis !== 'undefined') {
  globalThis.__axon_tests = __axon_tests;
  globalThis.__runAxonTests = __runAxonTests;
}

/** @typedef {number} HP */
/** @param {number} v @returns {boolean} */
const __validate_HP = (v) => (v >= 0) && (v <= 200);

/** @typedef {number} StatValue */
/** @param {number} v @returns {boolean} */
const __validate_StatValue = (v) => (v >= 1) && (v <= 20);

/** @typedef {number} Level */
/** @param {number} v @returns {boolean} */
const __validate_Level = (v) => (v >= 1) && (v <= 20);

/** @typedef {string} HeroName */
/** @param {string} v @returns {boolean} */
const __validate_HeroName = (v) => v.length > 0;

/** @typedef {string} ClassName */
/** @param {string} v @returns {boolean} */
const __validate_ClassName = (v) => v.length > 0;

/** @typedef {{
 *   name: string,
 *   heroClass: string,
 *   hp: number,
 *   maxHp: number,
 *   strength: number,
 *   defense: number,
 *   level: number,
 *   alive: boolean
 * }} Hero
 */

/** @typedef {{
 *   name: string,
 *   hp: number,
 *   maxHp: number,
 *   attack: number,
 *   defense: number,
 *   weakness: string,
 *   alive: boolean
 * }} Enemy
 */

const hero_is_alive = (h) => h.alive;

const any_alive = (party) => any(party, __x => __x.alive);

const format_attack_msg = (attacker, outcome, defender, dmg) => `${attacker} ${outcome} ${defender} for ${dmg} damage!`;

const format_death_msg = (name) => `${name} has fallen in battle.`;

const format_hero_label = (hero) => `${hero.name} Lv.${hero.level} ${hero.heroClass}`;

/**
 * Generate a visual HP bar string with percentage
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} hp
 * @param {number} maxHp
 * @returns {string}
 */
const hp_bar_text = (hp, maxHp) => {
  let filled = maxHp > 0 ? Math.max(0, Math.round(hp / maxHp * 8)) : 0;
  let bar = map(range(0, 8), i => i < filled ? "#" : ".");
  let pct = maxHp > 0 ? Math.floor(hp / maxHp * 100) : 0;
  let barStr = bar.join("");
  return `${barStr} ${hp}/${maxHp} (${pct}%)`;
};

/**
 * One-line hero status for the combat panel
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero} hero
 * @returns {string}
 */
const format_hero_card_line = (hero) => {
  let bar = hp_bar_text(hero.hp, hero.maxHp);
  let title = level_title(hero.level);
  return `${hero.name} the ${title}  ${bar}`;
};

/**
 * One-line enemy status for the combat panel
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Enemy} enemy
 * @returns {string}
 */
const format_enemy_card_line = (enemy) => {
  let bar = hp_bar_text(enemy.hp, enemy.maxHp);
  return `${enemy.name}  ${bar}`;
};

/**
 * Rank title based on level range
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} level
 * @returns {string}
 */
const level_title = (level) => ((_m) => (_m < 4) ? "Novice" : (_m < 7) ? "Adept" : (_m < 10) ? "Veteran" : "Master")(level);

/**
 * Narrative label for a d20 attack roll
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} roll
 * @returns {string}
 */
const combat_outcome_label = (roll) => ((_m) => (_m >= 20) ? "lands a perfect strike on" : (_m >= 18) ? "scores a CRITICAL HIT on" : (_m >= 8) ? "hits" : (_m >= 3) ? "grazes" : "misses")(roll);

/**
 * Extra damage when class targets enemy weakness — nested match on two axes
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} heroClass
 * @param {string} weakness
 * @returns {number}
 */
const element_bonus = (heroClass, weakness) => ((_m) => (_m === "mage") ? ((_m) => (_m === "arcane") ? 8 : (_m === "fire") ? 5 : 0)(weakness) : (_m === "ranger") ? ((_m) => (_m === "nature") ? 6 : (_m === "cold") ? 4 : 0)(weakness) : (_m === "knight") ? ((_m) => (_m === "physical") ? 5 : 0)(weakness) : 0)(heroClass);

/**
 * Single-char symbol for each hero class
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} heroClass
 * @returns {string}
 */
const class_symbol = (heroClass) => ((_m) => (_m === "mage") ? "[M]" : (_m === "knight") ? "[K]" : (_m === "ranger") ? "[R]" : "[?]")(heroClass);

/**
 * Display label for enemy weakness
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} weakness
 * @returns {string}
 */
const class_weakness_hint = (weakness) => ((_m) => (_m === "arcane") ? "weak to ARCANE (mage bonus)" : (_m === "fire") ? "weak to FIRE (mage bonus)" : (_m === "nature") ? "weak to NATURE (ranger bonus)" : (_m === "cold") ? "weak to COLD (ranger bonus)" : (_m === "physical") ? "weak to PHYSICAL (knight bonus)" : "no known weakness")(weakness);

/**
 * Core damage formula — memoized, same inputs always produce same damage
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} atk
 * @param {number} def
 * @param {number} bonus
 * @param {number} roll
 * @returns {number}
 */
const compute_damage = (() => {
  const __cache = new Map();
  return (atk, def, bonus, roll) => {
    const __key = JSON.stringify([atk, def, bonus, roll]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      let base = Math.max(1, atk + bonus - Math.floor(def / 2));
      let mult = roll >= 18 ? 2 : 1;
      return Math.max(1, base * mult);
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * Composite strength rating — memoized per unique hero state
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero} hero
 * @returns {number}
 */
const hero_power = (() => {
  const __cache = new Map();
  return (hero) => {
    const __key = JSON.stringify([hero]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return hero.strength * hero.level + Math.floor(hero.maxHp / 10);
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * Construct a Hero — all 5 typed params auto-validated at entry
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {HeroName} name
 * @param {ClassName} heroClass
 * @param {HP} hp
 * @param {StatValue} strength
 * @param {StatValue} defense
 * @param {Level} level
 * @returns {Hero}
 */
const create_hero = (name, heroClass, hp, strength, defense, level) => {
  if (!__validate_HeroName(name)) throw new Error(`AxonConstraintError: name violates HeroName constraint (got ${JSON.stringify(name)})`);
  if (!__validate_ClassName(heroClass)) throw new Error(`AxonConstraintError: heroClass violates ClassName constraint (got ${JSON.stringify(heroClass)})`);
  if (!__validate_HP(hp)) throw new Error(`AxonConstraintError: hp violates HP constraint (got ${JSON.stringify(hp)})`);
  if (!__validate_StatValue(strength)) throw new Error(`AxonConstraintError: strength violates StatValue constraint (got ${JSON.stringify(strength)})`);
  if (!__validate_StatValue(defense)) throw new Error(`AxonConstraintError: defense violates StatValue constraint (got ${JSON.stringify(defense)})`);
  if (!__validate_Level(level)) throw new Error(`AxonConstraintError: level violates Level constraint (got ${JSON.stringify(level)})`);
  return ({ name, heroClass, hp, maxHp: hp, strength, defense, level, alive: true });
};

/**
 * Living party members via .alive shorthand
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero[]} party
 * @returns {Hero[]}
 */
const alive_heroes = (party) => filter(party, __x => __x.alive);

/**
 * Names of all living heroes — chain of .field shorthands
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero[]} party
 * @returns {string}
 */
const party_names = (party) => map(filter(party, __x => __x.alive), __x => __x.name);

/**
 * Sum of living HP — .hp shorthand after .alive filter
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero[]} party
 * @returns {number}
 */
const total_party_hp = (() => {
  const __cache = new Map();
  return (party) => {
    const __key = JSON.stringify([party]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return sum(map(filter(party, __x => __x.alive), __x => __x.hp));
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * Sum of hero_power across all party members
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero[]} party
 * @returns {number}
 */
const party_power_rating = (() => {
  const __cache = new Map();
  return (party) => {
    const __key = JSON.stringify([party]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return sum(map(party, hero_power));
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * Count surviving heroes
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero[]} party
 * @returns {number}
 */
const count_alive = (party) => count(filter(party, __x => __x.alive));

/**
 * The hero with the highest power rating
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero[]} party
 * @returns {Hero}
 */
const strongest_hero = (party) => {
  let sorted = party.slice().sort((a, b) => hero_power(b) - hero_power(a));
  return first(sorted);
};

/**
 * Debug party state — @pure is false, checker will warn
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Hero[]} party
 * @returns {boolean}
 */
const debug_party = (party) => {
  console.log("debug_party:", map(party, __x => __x.name));
  return true;
};

/**
 * Return entity with updated hp and alive flag — no mutation
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {*} entity
 * @param {number} dmg
 * @returns {*}
 */
const apply_damage = (entity, dmg) => {
  let newHp = Math.max(0, entity.hp - dmg);
  return { ...entity, hp: newHp, alive: newHp > 0 };
};

/**
 * Create a DOM element with attributes and children
 * @effects dom.create, dom.attrs, dom.children
 * @param {string} tag
 * @param {Object} attrs
 * @param {*} ...children
 * @returns {Element}
 */
const el = (tag, attrs, ...children) => {
  let e = document.createElement(tag);
  Object.entries(attrs).forEach(([k, v]) => {
    if (k === "class") {
      return e.className = v;
    } else if (k === "id") {
      return e.id = v;
    } else if (k === "disabled") {
      return e.disabled = v;
    } else if (k === "type") {
      return e.type = v;
    } else if (k.startsWith("on")) {
      return e.addEventListener(k.slice(2).toLowerCase(), v);
    } else {
      return e.setAttribute(k, String(v));
    }
});
  children.flat().forEach((child) => {
    if (typeof child === "string") {
      return e.appendChild(document.createTextNode(child));
    } else if (child instanceof Node) {
      return e.appendChild(child);
    }
});
  return e;
};

/**
 * Render one hero row with HP bar and stats
 * @effects dom.create
 * @param {Hero} hero
 * @returns {Element}
 */
const render_hero_row = (hero) => {
  let sym = class_symbol(hero.heroClass);
  let label = format_hero_card_line(hero);
  let power = hero_power(hero);
  let pStr = `PWR:${power}`;
  let rowClass = hero.alive ? "hero-row" : "hero-row hero-dead";
  return el("div", { class: rowClass }, el("span", { class: "hero-sym" }, sym), el("span", { class: "hero-label" }, label), el("span", { class: "hero-pwr" }, pStr));
};

/**
 * Render the enemy status panel
 * @effects dom.create
 * @param {Enemy} enemy
 * @returns {Element}
 */
const render_enemy_panel = (enemy) => {
  let label = format_enemy_card_line(enemy);
  let hint = class_weakness_hint(enemy.weakness);
  let atkStr = `ATK:${enemy.attack}  DEF:${enemy.defense}`;
  return el("div", { class: "enemy-panel" }, el("div", { class: "enemy-name" }, enemy.name), el("div", { class: "enemy-bar" }, label), el("div", { class: "enemy-hint" }, hint), el("div", { class: "enemy-stats" }, atkStr));
};

/**
 * Render all hero rows with party-level stats
 * @effects dom.create
 * @param {Hero[]} party
 * @returns {Element}
 */
const render_party_panel = (party) => {
  let aliveCount = count_alive(party);
  let totalHp = total_party_hp(party);
  let powerRating = party_power_rating(party);
  let summaryStr = `Party: ${aliveCount} alive · ${totalHp} HP · PWR ${powerRating}`;
  let rows = map(party, render_hero_row);
  let container = el("div", { class: "party-panel" });
  rows.forEach(row => container.appendChild(row));
  container.appendChild(el("div", { class: "party-summary" }, summaryStr));
  return container;
};

/**
 * Bootstrap the combat engine — pure logic, thin DOM layer
 * @effects dom.write, dom.events, state.mutable, rng
 * @param {string} rootId
 * @returns {void}
 */
const render_combat = (rootId) => {
  let make_party = () => [create_hero("Aria", "mage", 60, 12, 5, 8), create_hero("Theron", "knight", 80, 8, 12, 6), create_hero("Lyra", "ranger", 70, 10, 7, 7)];
  let make_enemy = () => {
    return {
  name: "Shadow Drake",
  hp: 160,
  maxHp: 160,
  attack: 14,
  defense: 8,
  weakness: "arcane",
  alive: true
};
};
  let party = make_party();
  let enemy = make_enemy();
  let log_lines = [];
  let round_num = 0;
  let over = false;
  let root = document.getElementById(rootId);
  root.innerHTML = "";
  let partyEl = el("div", { class: "panel-party" });
  let enemyEl = el("div", { class: "panel-enemy" });
  let battleEl = el("div", { class: "battle-panels" });
  battleEl.appendChild(partyEl);
  battleEl.appendChild(enemyEl);
  let logEl = el("div", { class: "combat-log" });
  let attackBtn = el("button", { class: "btn-attack" }, "ATTACK");
  let resetBtn = el("button", { class: "btn-reset" }, "NEW BATTLE");
  let btnRow = el("div", { class: "btn-row" }, attackBtn, resetBtn);
  root.appendChild(battleEl);
  root.appendChild(logEl);
  root.appendChild(btnRow);
  let addLog = (msg) => {
    log_lines.push(msg);
    let entry = el("div", { class: "log-entry" }, msg);
    logEl.appendChild(entry);
    logEl.scrollTop = logEl.scrollHeight;
};
  let refresh = () => {
    partyEl.innerHTML = "";
    partyEl.appendChild(render_party_panel(party));
    enemyEl.innerHTML = "";
    enemyEl.appendChild(render_enemy_panel(enemy));
    return attackBtn.disabled = over;
};
  attackBtn.addEventListener("click", () => {
    let alive = alive_heroes(party);
    if (alive.length > 0 && enemy.alive && !over) {
      round_num = round_num + 1;
      addLog(`── Round ${round_num} ──`);
      let hi = Math.floor(Math.random() * alive.length);
      let hero = alive[hi];
      let roll = Math.floor(Math.random() * 20) + 1;
      let bonus = element_bonus(hero.heroClass, enemy.weakness);
      let dmg = compute_damage(hero.strength, enemy.defense, bonus, roll);
      let outcome = combat_outcome_label(roll);
      let eName = enemy.name;
      enemy = apply_damage(enemy, dmg);
      addLog(format_attack_msg(hero.name, outcome, eName, dmg));
      if (bonus > 0) {
        addLog(`  [elemental bonus: +${bonus} from ${hero.heroClass} vs ${enemy.weakness}]`);
      }
      if (!enemy.alive) {
        addLog(`** ${eName} has been slain! VICTORY! **`);
        over = true;
      }
      if (enemy.alive) {
        let ti = Math.floor(Math.random() * alive.length);
        let target = alive[ti];
        let eDmg = compute_damage(enemy.attack, target.defense, 0, 10);
        let dies = target.hp - eDmg <= 0;
        party = map(party, h => h.name === target.name ? apply_damage(h, eDmg) : h);
        addLog(format_attack_msg(eName, "strikes back at", target.name, eDmg));
        if (dies) {
          addLog(format_death_msg(target.name));
        }
        if (alive_heroes(party).length === 0) {
          addLog("** Your party has been defeated. GAME OVER. **");
          over = true;
        }
      }
      return refresh();
    }
});
  resetBtn.addEventListener("click", () => {
    party = make_party();
    enemy = make_enemy();
    log_lines = [];
    round_num = 0;
    over = false;
    logEl.innerHTML = "";
    addLog("A new battle begins.");
    addLog(`Shadow Drake emerges from the darkness — ${enemy.weakness}.`);
    return refresh();
});
  addLog("AXON COMBAT ENGINE — pure rules, memoized formulas, type-safe stats");
  addLog(`Shadow Drake appears — ${enemy.weakness}.`);
  addLog("Aria (mage) has arcane bonus vs this enemy.");
  addLog("Press ATTACK to begin.");
  return refresh();
};

