// Generated by Axon v0.4.0 transpiler
// DO NOT EDIT — source: .axn


// ── Axon v0.4.0 stdlib ──────────────────────────────────────────────────────

/**
 * Apply fn to every element of xs and return the results.
 * @pure @total
 * @param {Array} xs
 * @param {Function} fn
 * @returns {Array}
 */
const map = (xs, fn) => xs.map(fn);

/**
 * Keep only elements of xs for which pred returns true.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {Array}
 */
const filter = (xs, pred) => xs.filter(pred);

/**
 * Reduce xs to a single value, starting from init.
 * @pure @total
 * @param {Array} xs
 * @param {*} init
 * @param {Function} fn
 * @returns {*}
 */
const fold = (xs, init, fn) => xs.reduce(fn, init);

/**
 * Apply a sequence of single-argument functions left to right.
 * @pure @total
 * @param {...Function} fns
 * @returns {Function}
 */
const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);

/**
 * Combine two arrays element-by-element into pairs.
 * @pure @total
 * @param {Array} xs
 * @param {Array} ys
 * @returns {Array}
 */
const zip = (xs, ys) => xs.map((x, i) => [x, ys[i]]);

/**
 * Produce an array of integers from start (inclusive) to end (exclusive).
 * @pure @total
 * @param {number} start
 * @param {number} end
 * @returns {number[]}
 */
const range = (start, end) => Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);

/**
 * Return the first element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const first = (xs) => xs[0];

/**
 * Return the last element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const last = (xs) => xs[xs.length - 1];

/**
 * Sum a numeric array.
 * @pure @total
 * @param {number[]} xs
 * @returns {number}
 */
const sum = (xs) => xs.reduce((a, b) => a + b, 0);

/**
 * Count elements matching pred, or total length if no pred given.
 * @pure @total
 * @param {Array} xs
 * @param {Function} [pred]
 * @returns {number}
 */
const count = (xs, pred) => pred ? xs.filter(pred).length : xs.length;

/**
 * True if any element satisfies pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const any = (xs, pred) => xs.some(pred);

/**
 * True if all elements satisfy pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const all = (xs, pred) => xs.every(pred);

/**
 * Flatten one level of nesting.
 * @pure @total
 * @param {Array} xs
 * @returns {Array}
 */
const flat = (xs) => xs.flat();

/**
 * Group an array into a Map by key function.
 * @pure @total
 * @param {Array} xs
 * @param {Function} keyFn
 * @returns {Map}
 */
const groupBy = (xs, keyFn) => xs.reduce((m, x) => {
  const k = keyFn(x);
  if (!m.has(k)) m.set(k, []);
  m.get(k).push(x);
  return m;
}, new Map());

/**
 * Return a new object with only the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const pick = (obj, keys) => Object.fromEntries(keys.filter(k => k in obj).map(k => [k, obj[k]]));

/**
 * Return a new object without the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k]) => !keys.includes(k)));

// ── Axon built-in constraint validators ─────────────────────────────────────
// Generated by 'type T = base where ...' declarations.

const __axon_presets = {
  email:   /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  url:     /^https?:\/\//,
  uuid:    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  alpha:   /^[a-zA-Z]+$/,
  alnum:   /^[a-zA-Z0-9]+$/,
  numeric: /^[0-9]+$/,
  slug:    /^[a-z0-9-]+$/,
  hex:     /^#?[0-9a-fA-F]{3,8}$/,
};

// ── Axon v0.4.0 test runner ──────────────────────────────────────────────────
// @test declarations push entries here. Call __runAxonTests() to execute them.
// Also exposed on globalThis so the CLI's vm context can access it.

const __axon_tests = [];

/**
 * Run all registered @test declarations. Returns a result summary.
 * @returns {{ passed: number, failed: number, total: number, results: Array }}
 */
const __runAxonTests = () => {
  let passed = 0, failed = 0;
  const results = [];
  for (const t of __axon_tests) {
    try {
      const ok = !!t.fn();
      if (ok) {
        passed++;
        results.push({ ok: true,  desc: t.desc });
      } else {
        failed++;
        results.push({ ok: false, desc: t.desc, error: 'assertion returned false' });
      }
    } catch(e) {
      failed++;
      results.push({ ok: false, desc: t.desc, error: String(e) });
    }
  }
  return { passed, failed, total: passed + failed, results };
};
// Expose on globalThis so the Node CLI vm context and browser window can both access it
if (typeof globalThis !== 'undefined') {
  globalThis.__axon_tests = __axon_tests;
  globalThis.__runAxonTests = __runAxonTests;
}

/** @typedef {string} NonEmptyString */
/** @param {string} v @returns {boolean} */
const __validate_NonEmptyString = (v) => v.length > 0;

/** @typedef {string} EmailAddress */
/** @param {string} v @returns {boolean} */
const __validate_EmailAddress = (v) => __axon_presets.email.test(v);

/** @typedef {number} PositiveInt */
/** @param {number} v @returns {boolean} */
const __validate_PositiveInt = (v) => v > 0;

/** @typedef {number} Score */
/** @param {number} v @returns {boolean} */
const __validate_Score = (v) => (v >= 0) && (v <= 100);

/** @typedef {number} BoundedCount */
/** @param {number} v @returns {boolean} */
const __validate_BoundedCount = (v) => (v >= -10) && (v <= 10);

/** @typedef {string} CSSClass */
/** @param {string} v @returns {boolean} */
const __validate_CSSClass = (v) => v.length > 0;

/** @typedef {string} ThemeName */

/** @typedef {string} SlugString */
/** @param {string} v @returns {boolean} */
const __validate_SlugString = (v) => __axon_presets.slug.test(v);

/** @typedef {{
 *   count: number,
 *   min: number,
 *   max: number
 * }} CounterState
 */

/** @typedef {{
 *   valid: boolean,
 *   message: string,
 *   value: string
 * }} ValidationResult
 */

/** @typedef {{
 *   open: boolean,
 *   title: string,
 *   body: string
 * }} ModalState
 */

/** @typedef {{
 *   name: string,
 *   score: Score,
 *   active: boolean
 * }} Player
 */

const counter_make = (min, max, initial) => ({ count: Math.max(min, Math.min(max, initial)), min: min, max: max });

const counter_inc = (state) => ({ count: Math.min(state.count + 1, state.max), min: state.min, max: state.max });

const counter_dec = (state) => ({ count: Math.max(state.count - 1, state.min), min: state.min, max: state.max });

const counter_can_inc = (state) => state.count < state.max;

const counter_can_dec = (state) => state.count > state.min;

/**
 * Format counter value as a signed display string
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {CounterState} state
 * @returns {string}
 */
const counter_display = (state) => {
  let n = state.count;
  return ((_m) => (_m > 0) ? `+${n}` : (_m < 0) ? `${n}` : "0")(n);
};

const is_valid_email = (email) => __validate_EmailAddress(email);

/**
 * Produce a structured validation result with human-readable feedback
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} email
 * @returns {ValidationResult}
 */
const validate_email = (email) => ((_m) => (_m === 0) ? { valid: false, message: "Email is required", value: email } : ((_m) => (_m === true) ? { valid: true, message: "Looks good!", value: email } : (_m === false) ? { valid: false, message: "Enter a valid email address", value: email } : undefined)(is_valid_email(email)))(email.length);

const validation_css_class = (result) => result.valid ? "field-valid" : result.value.length === 0 ? "field-empty" : "field-invalid";

const toggle_flip = (state) => !state;

const toggle_label = (state, onLabel, offLabel) => state ? onLabel : offLabel;

const toggle_css_class = (state, baseClass) => state ? `${baseClass} ${baseClass}--on` : `${baseClass} ${baseClass}--off`;

const theme_class = (name) => `theme-${name}`;

const theme_next = (current, available) => available[(available.indexOf(current) + 1) % available.length];

/**
 * Human-readable display label for a named theme
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {ThemeName} name
 * @returns {string}
 */
const theme_label = (name) => ((_m) => (_m === "light") ? "Light" : (_m === "dark") ? "Dark" : (_m === "synthwave") ? "Synthwave" : name)(name);

const modal_open = (title, body) => ({ open: true, title: title, body: body });

const modal_close = (state) => ({ open: false, title: state.title, body: state.body });

/**
 * Format a welcome message — params are auto-validated at the boundary
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {EmailAddress} email
 * @param {NonEmptyString} name
 * @returns {string}
 */
const send_welcome = (email, name) => {
  if (!__validate_EmailAddress(email)) throw new Error(`AxonConstraintError: email violates EmailAddress constraint (got ${JSON.stringify(email)})`);
  if (!__validate_NonEmptyString(name)) throw new Error(`AxonConstraintError: name violates NonEmptyString constraint (got ${JSON.stringify(name)})`);
  return `Welcome, ${name}! A confirmation has been sent to ${email}.`;
};

/**
 * Format a score label — Score type ensures 0-100, NonEmptyString ensures label exists
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {NonEmptyString} label
 * @param {Score} value
 * @returns {string}
 */
const format_score = (label, value) => {
  if (!__validate_NonEmptyString(label)) throw new Error(`AxonConstraintError: label violates NonEmptyString constraint (got ${JSON.stringify(label)})`);
  if (!__validate_Score(value)) throw new Error(`AxonConstraintError: value violates Score constraint (got ${JSON.stringify(value)})`);
  return `${label}: ${value}/100`;
};

/**
 * Sum the counts from an array of counter states
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {CounterState[]} states
 * @returns {number}
 */
const counter_history_total = (states) => sum(map(states, __x => __x.count));

/**
 * Get names of all active players
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Player[]} players
 * @returns {string}
 */
const top_players = (players) => map(filter(players, __x => __x.active), __x => __x.name);

/**
 * Sum all player scores
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Player[]} players
 * @returns {number}
 */
const total_score = (players) => sum(map(players, __x => __x.score));

/**
 * Classic recursive Fibonacci — automatically memoized by @memo
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} n
 * @returns {number}
 */
const fibonacci = (() => {
  const __cache = new Map();
  return (n) => {
    const __key = JSON.stringify([n]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return ((_m) => (_m === 0) ? 0 : (_m === 1) ? 1 : fibonacci(n - 1) + fibonacci(n - 2))(n);
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * n*(n+1)/2 — memoized for repeated calls with same n
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} n
 * @returns {number}
 */
const triangle_number = (() => {
  const __cache = new Map();
  return (n) => {
    const __key = JSON.stringify([n]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return n * (n + 1) / 2;
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * Validate every email in a list and return all results
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} emails
 * @returns {ValidationResult[]}
 */
const validate_email_batch = (emails) => map(emails, validate_email);

/**
 * Count how many emails in a list pass validation
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} emails
 * @returns {number}
 */
const count_valid_emails = (emails) => count(filter(emails, is_valid_email));

/**
 * Return the first invalid email, or empty string if all pass
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} emails
 * @returns {string}
 */
const first_invalid_email = (emails) => {
  let invalid = filter(emails, e => !is_valid_email(e));
  return invalid.length > 0 ? first(invalid) : "";
};

/**
 * Map theme names to their display labels
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} themes
 * @returns {string}
 */
const theme_options = (themes) => map(themes, theme_label);

/**
 * True if any counter state has reached its maximum value
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {CounterState[]} states
 * @returns {boolean}
 */
const any_at_max = (states) => any(states, s => s.count === s.max);

/**
 * Validate email with debug logging — intentionally impure to demo checker
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} email
 * @returns {boolean}
 */
const debug_validate = (email) => {
  let result = is_valid_email(email);
  console.log("debug_validate:", email, "->", result);
  return result;
};

/**
 * Create a DOM element, apply attributes, and append children
 * @effects dom.create, dom.attrs, dom.children
 * @param {string} tag
 * @param {Object} attrs
 * @param {*} ...children
 * @returns {Element}
 */
const el = (tag, attrs, ...children) => {
  let e = document.createElement(tag);
  Object.entries(attrs).forEach(([k, v]) => {
    if (k === "class") {
      return e.className = v;
    } else if (k === "disabled") {
      return e.disabled = v;
    } else if (k === "checked") {
      return e.checked = v;
    } else if (k.startsWith("on")) {
      return e.addEventListener(k.slice(2).toLowerCase(), v);
    } else if (k === "placeholder") {
      return e.placeholder = v;
    } else if (k === "type") {
      return e.type = v;
    } else if (k === "value") {
      return e.value = v;
    } else if (k === "id") {
      return e.id = v;
    } else if (k === "for") {
      return e.setAttribute("for", v);
    } else {
      return e.setAttribute(k, String(v));
    }
});
  children.flat().forEach((child) => {
    if (typeof child === "string") {
      return e.appendChild(document.createTextNode(child));
    } else if (child instanceof Node) {
      return e.appendChild(child);
    }
});
  return e;
};

/**
 * Append a child element into a container by ID
 * @effects dom.write
 * @param {string} containerId
 * @param {Element} child
 * @returns {void}
 */
const mount = (containerId, child) => {
  let container = document.getElementById(containerId);
  return container.appendChild(child);
};

/**
 * Mount a stateful counter widget
 * @effects dom.write, dom.events, state.mutable
 * @param {string} containerId
 * @returns {void}
 */
const render_counter = (containerId) => {
  let state = counter_make(-10, 10, 0);
  let display = el("span", { class: "counter-value" }, counter_display(state));
  let decBtn = el("button", { class: "btn btn-ghost" }, "−");
  let incBtn = el("button", { class: "btn btn-ghost" }, "+");
  decBtn.addEventListener("click", () => {
    state = counter_dec(state);
    display.textContent = counter_display(state);
    decBtn.disabled = !counter_can_dec(state);
    return incBtn.disabled = !counter_can_inc(state);
});
  incBtn.addEventListener("click", () => {
    state = counter_inc(state);
    display.textContent = counter_display(state);
    decBtn.disabled = !counter_can_dec(state);
    return incBtn.disabled = !counter_can_inc(state);
});
  return mount(containerId, el("div", { class: "counter-widget" }, decBtn, display, incBtn));
};

/**
 * Mount an email input widget with live validation feedback
 * @effects dom.write, dom.events, state.mutable
 * @param {string} containerId
 * @returns {void}
 */
const render_email_validator = (containerId) => {
  let input = el("input", {
  type: "email",
  class: "input-field",
  placeholder: "you@example.com",
  id: "email-input"
});
  let feedback = el("span", { class: "field-empty feedback-msg" }, "Enter your email");
  input.addEventListener("input", () => {
    let result = validate_email(input.value);
    feedback.textContent = result.message;
    feedback.className = validation_css_class(result) + " feedback-msg";
    return input.className = "input-field " + validation_css_class(result);
});
  return mount(containerId, el("div", { class: "validator-widget" }, el("label", { for: "email-input", class: "field-label" }, "Email Address"), input, feedback));
};

/**
 * Mount a toggle switch that flips between two labelled states
 * @effects dom.write, dom.events, state.mutable
 * @param {string} containerId
 * @param {string} onLabel
 * @param {string} offLabel
 * @returns {void}
 */
const render_toggle = (containerId, onLabel, offLabel) => {
  let state = false;
  let track = el("div", { class: toggle_css_class(state, "toggle-track") });
  let thumb = el("div", { class: "toggle-thumb" });
  let label = el("span", { class: "toggle-label" }, toggle_label(state, onLabel, offLabel));
  track.appendChild(thumb);
  let btn = el("button", { class: "toggle-btn" }, track, label);
  btn.addEventListener("click", () => {
    state = toggle_flip(state);
    track.className = toggle_css_class(state, "toggle-track");
    return label.textContent = toggle_label(state, onLabel, offLabel);
});
  return mount(containerId, btn);
};

/**
 * Mount a button that cycles through available themes
 * @effects dom.write, dom.events, state.mutable
 * @param {string} containerId
 * @returns {void}
 */
const render_theme_switcher = (containerId) => {
  let themes = ["light", "dark", "synthwave"];
  let labels = theme_options(themes);
  let current = 0;
  document.body.className = theme_class(themes[current]);
  let lbl = el("span", { class: "theme-label" }, labels[current]);
  let ico = el("span", { class: "theme-icon" }, "◐");
  let btn = el("button", { class: "btn btn-theme" }, ico, lbl);
  btn.addEventListener("click", () => {
    current = (current + 1) % themes.length;
    document.body.className = theme_class(themes[current]);
    return lbl.textContent = labels[current];
});
  return mount(containerId, btn);
};

/**
 * Mount a button that opens a modal dialog
 * @effects dom.write, dom.events, state.mutable
 * @param {string} containerId
 * @returns {void}
 */
const render_modal_demo = (containerId) => {
  let state = modal_close({ open: false, title: "", body: "" });
  let closeBtn = el("button", { class: "btn btn-primary modal-close-btn" }, "Close");
  let overlay = el("div", { class: "modal-overlay" }, el("div", { class: "modal-box" }, el("h3", { class: "modal-title" }, "Hello from Axon"), el("p", { class: "modal-body" }, "This modal state is managed by pure Axon functions. " + "Opening and closing are just state transitions — no framework needed."), closeBtn));
  let openBtn = el("button", { class: "btn btn-primary", id: "modal-open" }, "Open Modal");
  openBtn.addEventListener("click", () => {
    state = modal_open("Hello from Axon", "Pure state logic");
    return overlay.style.display = "flex";
});
  closeBtn.addEventListener("click", () => {
    state = modal_close(state);
    return overlay.style.display = "none";
});
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) {
      state = modal_close(state);
      return overlay.style.display = "none";
    }
});
  document.body.appendChild(overlay);
  return mount(containerId, openBtn);
};

