// Auto-generated by tools/embed_music.js — do not edit manually
window.MUSIC_SOURCES = {
  axn: `// ═══════════════════════════════════════════════════════════════════════════════
// Axon v0.4.0 — Synthwave Music Library
//
// Every feature from v0.1 through v0.3, demonstrated in one coherent app:
//
//   v0.1  type aliases · records · @intent · @pure · @total · @effects
//         pipeline |> · match patterns · let bindings
//   v0.2  where constraints · short-form fn · stdlib (map/filter/sum/count/any)
//         @pure checker · @exhaustive checker
//   v0.3  string interpolation "{name}" · .field accessor shorthand
//         param validation injection · @memo memoization
// ═══════════════════════════════════════════════════════════════════════════════

// ── v0.2: Constrained types ───────────────────────────────────────────────────
// Every \`where\` clause generates a __validate_T(v) function at compile time.
// Functions typed with these as params get auto-injected guards (v0.3 feature).

type BPM        = int    where >= 60 && <= 200
type Duration   = int    where > 0
type TrackTitle = string where length > 0
type ArtistName = string where length > 0
type Volume     = int    where >= 0 && <= 100

// ── v0.1: Record declarations ─────────────────────────────────────────────────

record Track {
  id: int
  title: string
  artist: string
  bpm: int
  duration: int
  genre: string
  featured: bool
}

record LibraryStats {
  count: int
  totalDuration: int
  avgBpm: int
  featuredCount: int
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.2: SHORT-FORM FUNCTIONS
// Single-expression functions with no type signature.
// ══════════════════════════════════════════════════════════════════════════════

fn track_is_featured(t) = t.featured

// Helper used in format_duration
fn pad2(n) = n < 10 ? "0" + String(n) : String(n)

// v0.3: string interpolation — {t.title} and {t.artist} are ident.prop forms
fn format_track_label(t) = "{t.title} · {t.artist}"

// v0.3: {bpm} is interpolated, " BPM" is literal
fn format_bpm_tag(bpm) = "{bpm} BPM"

// v0.3: format_fibonacci_result uses two idents in one interpolated string
fn format_fibonacci_result(n, result) = "fib({n}) = {result}"

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: STRING INTERPOLATION in full-form functions
// Local let bindings are used as interpolation targets.
// ══════════════════════════════════════════════════════════════════════════════

fn format_duration :: (secs: Duration) -> string {
  @pure @total
  @intent "Format seconds as M:SS display string"
  let m = Math.floor(secs / 60)
  let s = pad2(secs % 60)
  "{m}:{s}"
}

fn format_stats_line :: (stats: LibraryStats) -> string {
  @pure @total
  @intent "Render a compact one-line summary of library state"
  let n    = stats.count
  let mins = Math.floor(stats.totalDuration / 60)
  let avg  = stats.avgBpm
  let feat = stats.featuredCount
  "{n} tracks · {mins} min · avg {avg} BPM · {feat} featured"
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: PARAM VALIDATION INJECTION
// The compiler auto-injects __validate_T guards for constrained-type params.
// No manual validation calls — these guards appear in the transpiled output.
// ══════════════════════════════════════════════════════════════════════════════

fn create_track :: (id: int, title: TrackTitle, artist: ArtistName, bpm: BPM, duration: Duration, genre: string) -> Track {
  @pure @total
  @intent "Construct a Track — BPM/Duration/TrackTitle/ArtistName guards injected at entry"
  { id, title, artist, bpm, duration, genre, featured: false }
}

fn set_volume :: (vol: Volume) -> string {
  @pure @total
  @intent "Format a volume level string — Volume must be 0-100 or auto-guard throws"
  "Volume set to {vol}%"
}

// Pre-validation helper for the add-track form (user-facing errors)
fn validate_track_input :: (title: string, artist: string, bpm: int, duration: int) -> string {
  @pure @total
  @intent "Return the first validation error for new track fields, or empty string if valid"
  title.length === 0   ? "Title cannot be empty" :
  artist.length === 0  ? "Artist cannot be empty" :
  bpm < 60             ? "BPM too low (minimum is 60)" :
  bpm > 200            ? "BPM too high (maximum is 200)" :
  duration <= 0        ? "Duration must be greater than 0" :
  ""
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.1: PATTERN MATCHING
// ══════════════════════════════════════════════════════════════════════════════

fn tempo_label :: (bpm: int) -> string {
  @pure @total
  @intent "Classify BPM range as a human-readable tempo label"
  match bpm {
    | < 90  => "Slow"
    | < 120 => "Moderate"
    | < 150 => "Fast"
    | _     => "Intense"
  }
}

fn genre_css_class :: (genre: string) -> string {
  @pure @total
  @intent "Map genre identifier to its accent color CSS class"
  match genre {
    | "synthwave"  => "g-sw"
    | "darksynth"  => "g-ds"
    | "ambient"    => "g-amb"
    | "retrowave"  => "g-rw"
    | "cyberpunk"  => "g-cp"
    | _            => "g-default"
  }
}

fn genre_short :: (genre: string) -> string {
  @pure @total
  @intent "Abbreviated tag for a genre badge"
  match genre {
    | "synthwave"  => "SW"
    | "darksynth"  => "DS"
    | "ambient"    => "AMB"
    | "retrowave"  => "RW"
    | "cyberpunk"  => "CP"
    | _            => genre
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: @MEMO — automatic memoization at compile time
// @pure @total @memo functions are wrapped in a Map-based cache closure.
// The cache key is JSON.stringify([...args]).
// ══════════════════════════════════════════════════════════════════════════════

fn library_stats :: (tracks: Track[]) -> LibraryStats {
  @pure @total @memo
  @intent "Aggregate stats across the track collection — memoized, O(1) on repeated calls"
  let total_dur  = tracks |> map(.duration) |> sum
  let total_bpm  = tracks |> map(.bpm) |> sum
  let n_featured = tracks |> filter(.featured) |> count
  {
    count: tracks.length,
    totalDuration: total_dur,
    avgBpm: tracks.length > 0 ? Math.round(total_bpm / tracks.length) : 0,
    featuredCount: n_featured
  }
}

fn fibonacci :: (n: int) -> int {
  @pure @total @memo
  @intent "Classic recursive Fibonacci — @memo turns O(2^n) into O(n) via Map cache"
  match n {
    | 0 => 0
    | 1 => 1
    | _ => fibonacci(n-1) + fibonacci(n-2)
  }
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.3: .FIELD ACCESSOR SHORTHAND in pipelines
// .fieldName creates an implicit lambda __x => __x.fieldName.
// Makes filter/map intent immediately readable — no ceremony.
// ══════════════════════════════════════════════════════════════════════════════

fn featured_tracks :: (tracks: Track[]) -> Track[] {
  @pure @total
  @intent "Return only featured tracks using .featured shorthand"
  tracks |> filter(.featured)
}

fn all_titles :: (tracks: Track[]) -> string[] {
  @pure @total
  @intent "Extract all track titles using .title shorthand"
  tracks |> map(.title)
}

fn all_artists :: (tracks: Track[]) -> string[] {
  @pure @total
  @intent "Extract all artist names using .artist shorthand"
  tracks |> map(.artist)
}

fn total_playtime :: (tracks: Track[]) -> int {
  @pure @total
  @intent "Sum all durations using .duration shorthand"
  tracks |> map(.duration) |> sum
}

// ══════════════════════════════════════════════════════════════════════════════
// v0.2: STDLIB SHOWCASE
// ══════════════════════════════════════════════════════════════════════════════

fn tracks_in_genre :: (tracks: Track[], genre: string) -> Track[] {
  @pure @total
  @intent "Filter tracks to a specific genre"
  tracks |> filter(t => t.genre === genre)
}

fn any_featured :: (tracks: Track[]) -> bool {
  @pure @total
  @intent "True if the collection has at least one featured track"
  tracks |> any(.featured)
}

fn top_by_bpm :: (tracks: Track[], n: int) -> Track[] {
  @pure @total
  @intent "Return the top n tracks by BPM descending"
  let sorted = tracks.slice().sort((a, b) => b.bpm - a.bpm)
  sorted.slice(0, n)
}

// @pure checker demo: intentionally impure function warns at compile time
fn debug_track :: (track: Track) -> bool {
  @pure @total
  @intent "Debug-log a track — @pure is a lie, checker will warn"
  let _ = console.log("debug_track:", track.title)
  true
}

// ══════════════════════════════════════════════════════════════════════════════
// DOM BUILDER — thin imperative layer, @effects declared explicitly
// ══════════════════════════════════════════════════════════════════════════════

fn el :: (tag: string, attrs: object, ...children: any[]) -> Element {
  @effects [dom.create, dom.attrs, dom.children]
  @intent "Create a DOM element, set attributes, and append children"
  let e = document.createElement(tag)
  let _ = Object.entries(attrs).forEach(([k, v]) => {
    if (k === "class") { e.className = v }
    else if (k === "id") { e.id = v }
    else if (k === "disabled") { e.disabled = v }
    else if (k === "value") { e.value = v }
    else if (k === "placeholder") { e.placeholder = v }
    else if (k === "type") { e.type = v }
    else if (k === "for") { e.setAttribute("for", v) }
    else if (k.startsWith("on")) { e.addEventListener(k.slice(2).toLowerCase(), v) }
    else { e.setAttribute(k, String(v)) }
  })
  let _ = children.flat().forEach(child => {
    if (typeof child === "string") { e.appendChild(document.createTextNode(child)) }
    else if (child instanceof Node) { e.appendChild(child) }
  })
  e
}

fn mount_into :: (container: Element, child: Element) -> void {
  @effects [dom.write]
  @intent "Append a child element into a container element directly"
  container.appendChild(child)
}

// ── Track card ────────────────────────────────────────────────────────────────

fn render_track_card :: (track: Track) -> Element {
  @effects [dom.create]
  @intent "Render a single track as a styled card"
  let label  = format_track_label(track)
  let dur    = format_duration(track.duration)
  let bpmtag = format_bpm_tag(track.bpm)
  let tempo  = tempo_label(track.bpm)
  let gclass = genre_css_class(track.genre)
  let gtag   = genre_short(track.genre)
  let cardClass = track.featured ? "track-card track-featured" : "track-card"
  el("div", { class: cardClass },
    el("div", { class: "track-main" },
      el("div", { class: "track-label" }, label),
      el("div", { class: "track-badges" },
        el("span", { class: "badge genre-badge " + gclass }, gtag),
        el("span", { class: "badge tempo-badge" }, tempo),
        el("span", { class: "badge dur-badge" }, dur),
        el("span", { class: "badge bpm-badge" }, bpmtag)
      )
    ),
    track.featured ? el("div", { class: "featured-mark" }, "FEATURED") : el("span", {})
  )
}

// ── Stats bar ─────────────────────────────────────────────────────────────────

fn render_stats_bar :: (tracks: Track[]) -> Element {
  @effects [dom.create]
  @intent "Render the live library stats and @memo benchmark badge"
  let stats = library_stats(tracks)
  let line  = format_stats_line(stats)
  let fib35 = fibonacci(35)
  let fibLabel = format_fibonacci_result(35, fib35)
  el("div", { class: "stats-bar" },
    el("span", { class: "stats-text" }, line),
    el("span", { class: "memo-badge" }, fibLabel + " (@memo)")
  )
}

// ── Genre filter row ──────────────────────────────────────────────────────────

fn render_genre_filters :: (genres: string[], activeGenre: string, onFilter: any) -> Element {
  @effects [dom.create]
  @intent "Render genre filter pills — active genre is highlighted"
  let buttons = genres |> map(g =>
    el("button", { class: g === activeGenre ? "filter-btn filter-btn--active" : "filter-btn" },
      g === "all" ? "All Tracks" : g
    )
  )
  let _ = genres.forEach((g, i) => {
    let btn = buttons[i]
    let _ = btn.addEventListener("click", () => onFilter(g))
  })
  el("div", { class: "filter-row" }, ...buttons)
}

// ── Add track form ────────────────────────────────────────────────────────────

fn render_add_form :: (container: Element, onAdd: any) -> void {
  @effects [dom.write, dom.create, dom.events]
  @intent "Render an add-track form that demonstrates param validation injection"
  let titleIn  = el("input", { type: "text",   class: "form-inp", placeholder: "Title (required)" })
  let artistIn = el("input", { type: "text",   class: "form-inp", placeholder: "Artist (required)" })
  let bpmIn    = el("input", { type: "number", class: "form-inp", placeholder: "BPM 60-200" })
  let durIn    = el("input", { type: "number", class: "form-inp", placeholder: "Duration (seconds)" })
  let genreIn  = el("input", { type: "text",   class: "form-inp", placeholder: "Genre (optional)" })
  let errEl    = el("div",   { class: "form-err" })
  let addBtn   = el("button", { class: "add-btn" }, "Add Track")
  let _ = addBtn.addEventListener("click", () => {
    let title  = titleIn.value
    let artist = artistIn.value
    let bpm    = parseInt(bpmIn.value)
    let dur    = parseInt(durIn.value)
    let genre  = genreIn.value.length > 0 ? genreIn.value : "other"
    let err    = validate_track_input(title, artist, bpm, dur)
    if (err.length > 0) {
      errEl.textContent = err
    } else {
      errEl.textContent = ""
      let newId = Math.floor(Math.random() * 9000) + 1000
      let track = create_track(newId, title, artist, bpm, dur, genre)
      let _ = onAdd(track)
      let _ = titleIn.value  = ""
      let _ = artistIn.value = ""
      let _ = bpmIn.value    = ""
      let _ = durIn.value    = ""
      let _ = genreIn.value  = ""
    }
  })
  let _ = container.appendChild(
    el("div", { class: "add-form" },
      el("div", { class: "form-header" },
        el("h3", { class: "form-title" }, "Add Track"),
        el("p", { class: "form-note" },
          "create_track() has auto-injected guards for BPM (60-200), Duration (> 0), " +
          "TrackTitle and ArtistName (non-empty). See the transpiled JS tab."
        )
      ),
      el("div", { class: "form-fields" },
        el("div", { class: "form-row" }, titleIn, artistIn),
        el("div", { class: "form-row" }, bpmIn, durIn, genreIn)
      ),
      errEl,
      addBtn
    )
  )
}

// ── Main library renderer ─────────────────────────────────────────────────────

fn render_library :: (rootId: string, initialTracks: any[]) -> void {
  @effects [dom.write, dom.events, state.mutable]
  @intent "Bootstrap and mount the full music library UI into a root container"
  let tracks      = initialTracks.slice()
  let activeGenre = "all"
  let genres      = ["all", "synthwave", "darksynth", "ambient", "retrowave", "cyberpunk"]

  let root = document.getElementById(rootId)
  let _ = root.innerHTML = ""

  // Build layout skeleton — children with IDs for refresh targeting
  let statsEl   = el("div", { class: "stats-section" })
  let filtersEl = el("div", { class: "filters-section" })
  let listEl    = el("div", { class: "track-list" })
  let formEl    = el("div", { class: "form-section" })
  let _ = root.appendChild(statsEl)
  let _ = root.appendChild(filtersEl)
  let _ = root.appendChild(listEl)
  let _ = root.appendChild(formEl)

  // refresh re-renders the live parts (stats, filters, track list)
  let refresh = () => {
    statsEl.innerHTML = ""
    let _ = statsEl.appendChild(render_stats_bar(tracks))
    filtersEl.innerHTML = ""
    let _ = filtersEl.appendChild(render_genre_filters(genres, activeGenre, (genre) => {
      activeGenre = genre
      refresh()
    }))
    listEl.innerHTML = ""
    let visible = activeGenre === "all" ? tracks : tracks_in_genre(tracks, activeGenre)
    let _ = visible.forEach(t => listEl.appendChild(render_track_card(t)))
  }

  // Add form only rendered once — calls refresh when a track is successfully added
  render_add_form(formEl, (track) => {
    tracks = [...tracks, track]
    refresh()
  })

  refresh()
}
`,
  js:  `// Generated by Axon v0.4.0 transpiler
// DO NOT EDIT — source: .axn


// ── Axon v0.4.0 stdlib ──────────────────────────────────────────────────────

/**
 * Apply fn to every element of xs and return the results.
 * @pure @total
 * @param {Array} xs
 * @param {Function} fn
 * @returns {Array}
 */
const map = (xs, fn) => xs.map(fn);

/**
 * Keep only elements of xs for which pred returns true.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {Array}
 */
const filter = (xs, pred) => xs.filter(pred);

/**
 * Reduce xs to a single value, starting from init.
 * @pure @total
 * @param {Array} xs
 * @param {*} init
 * @param {Function} fn
 * @returns {*}
 */
const fold = (xs, init, fn) => xs.reduce(fn, init);

/**
 * Apply a sequence of single-argument functions left to right.
 * @pure @total
 * @param {...Function} fns
 * @returns {Function}
 */
const pipe = (...fns) => (x) => fns.reduce((v, f) => f(v), x);

/**
 * Combine two arrays element-by-element into pairs.
 * @pure @total
 * @param {Array} xs
 * @param {Array} ys
 * @returns {Array}
 */
const zip = (xs, ys) => xs.map((x, i) => [x, ys[i]]);

/**
 * Produce an array of integers from start (inclusive) to end (exclusive).
 * @pure @total
 * @param {number} start
 * @param {number} end
 * @returns {number[]}
 */
const range = (start, end) => Array.from({ length: Math.max(0, end - start) }, (_, i) => start + i);

/**
 * Return the first element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const first = (xs) => xs[0];

/**
 * Return the last element of an array, or undefined if empty.
 * @pure @total
 * @param {Array} xs
 * @returns {*}
 */
const last = (xs) => xs[xs.length - 1];

/**
 * Sum a numeric array.
 * @pure @total
 * @param {number[]} xs
 * @returns {number}
 */
const sum = (xs) => xs.reduce((a, b) => a + b, 0);

/**
 * Count elements matching pred, or total length if no pred given.
 * @pure @total
 * @param {Array} xs
 * @param {Function} [pred]
 * @returns {number}
 */
const count = (xs, pred) => pred ? xs.filter(pred).length : xs.length;

/**
 * True if any element satisfies pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const any = (xs, pred) => xs.some(pred);

/**
 * True if all elements satisfy pred.
 * @pure @total
 * @param {Array} xs
 * @param {Function} pred
 * @returns {boolean}
 */
const all = (xs, pred) => xs.every(pred);

/**
 * Flatten one level of nesting.
 * @pure @total
 * @param {Array} xs
 * @returns {Array}
 */
const flat = (xs) => xs.flat();

/**
 * Group an array into a Map by key function.
 * @pure @total
 * @param {Array} xs
 * @param {Function} keyFn
 * @returns {Map}
 */
const groupBy = (xs, keyFn) => xs.reduce((m, x) => {
  const k = keyFn(x);
  if (!m.has(k)) m.set(k, []);
  m.get(k).push(x);
  return m;
}, new Map());

/**
 * Return a new object with only the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const pick = (obj, keys) => Object.fromEntries(keys.filter(k => k in obj).map(k => [k, obj[k]]));

/**
 * Return a new object without the listed keys.
 * @pure @total
 * @param {Object} obj
 * @param {string[]} keys
 * @returns {Object}
 */
const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k]) => !keys.includes(k)));

// ── Axon built-in constraint validators ─────────────────────────────────────
// Generated by 'type T = base where ...' declarations.

const __axon_presets = {
  email:   /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+\$/,
  url:     /^https?:\\/\\//,
  uuid:    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\$/i,
  alpha:   /^[a-zA-Z]+\$/,
  alnum:   /^[a-zA-Z0-9]+\$/,
  numeric: /^[0-9]+\$/,
  slug:    /^[a-z0-9-]+\$/,
  hex:     /^#?[0-9a-fA-F]{3,8}\$/,
};

// ── Axon v0.4.0 test runner ──────────────────────────────────────────────────
// @test declarations push entries here. Call __runAxonTests() to execute them.
// Also exposed on globalThis so the CLI's vm context can access it.

const __axon_tests = [];

/**
 * Run all registered @test declarations. Returns a result summary.
 * @returns {{ passed: number, failed: number, total: number, results: Array }}
 */
const __runAxonTests = () => {
  let passed = 0, failed = 0;
  const results = [];
  for (const t of __axon_tests) {
    try {
      const ok = !!t.fn();
      if (ok) {
        passed++;
        results.push({ ok: true,  desc: t.desc });
      } else {
        failed++;
        results.push({ ok: false, desc: t.desc, error: 'assertion returned false' });
      }
    } catch(e) {
      failed++;
      results.push({ ok: false, desc: t.desc, error: String(e) });
    }
  }
  return { passed, failed, total: passed + failed, results };
};
// Expose on globalThis so the Node CLI vm context and browser window can both access it
if (typeof globalThis !== 'undefined') {
  globalThis.__axon_tests = __axon_tests;
  globalThis.__runAxonTests = __runAxonTests;
}

/** @typedef {number} BPM */
/** @param {number} v @returns {boolean} */
const __validate_BPM = (v) => (v >= 60) && (v <= 200);

/** @typedef {number} Duration */
/** @param {number} v @returns {boolean} */
const __validate_Duration = (v) => v > 0;

/** @typedef {string} TrackTitle */
/** @param {string} v @returns {boolean} */
const __validate_TrackTitle = (v) => v.length > 0;

/** @typedef {string} ArtistName */
/** @param {string} v @returns {boolean} */
const __validate_ArtistName = (v) => v.length > 0;

/** @typedef {number} Volume */
/** @param {number} v @returns {boolean} */
const __validate_Volume = (v) => (v >= 0) && (v <= 100);

/** @typedef {{
 *   id: number,
 *   title: string,
 *   artist: string,
 *   bpm: number,
 *   duration: number,
 *   genre: string,
 *   featured: boolean
 * }} Track
 */

/** @typedef {{
 *   count: number,
 *   totalDuration: number,
 *   avgBpm: number,
 *   featuredCount: number
 * }} LibraryStats
 */

const track_is_featured = (t) => t.featured;

const pad2 = (n) => n < 10 ? "0" + String(n) : String(n);

const format_track_label = (t) => \`\${t.title} · \${t.artist}\`;

const format_bpm_tag = (bpm) => \`\${bpm} BPM\`;

const format_fibonacci_result = (n, result) => \`fib(\${n}) = \${result}\`;

/**
 * Format seconds as M:SS display string
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Duration} secs
 * @returns {string}
 */
const format_duration = (secs) => {
  if (!__validate_Duration(secs)) throw new Error(\`AxonConstraintError: secs violates Duration constraint (got \${JSON.stringify(secs)})\`);
  let m = Math.floor(secs / 60);
  let s = pad2(secs % 60);
  return \`\${m}:\${s}\`;
};

/**
 * Render a compact one-line summary of library state
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {LibraryStats} stats
 * @returns {string}
 */
const format_stats_line = (stats) => {
  let n = stats.count;
  let mins = Math.floor(stats.totalDuration / 60);
  let avg = stats.avgBpm;
  let feat = stats.featuredCount;
  return \`\${n} tracks · \${mins} min · avg \${avg} BPM · \${feat} featured\`;
};

/**
 * Construct a Track — BPM/Duration/TrackTitle/ArtistName guards injected at entry
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} id
 * @param {TrackTitle} title
 * @param {ArtistName} artist
 * @param {BPM} bpm
 * @param {Duration} duration
 * @param {string} genre
 * @returns {Track}
 */
const create_track = (id, title, artist, bpm, duration, genre) => {
  if (!__validate_TrackTitle(title)) throw new Error(\`AxonConstraintError: title violates TrackTitle constraint (got \${JSON.stringify(title)})\`);
  if (!__validate_ArtistName(artist)) throw new Error(\`AxonConstraintError: artist violates ArtistName constraint (got \${JSON.stringify(artist)})\`);
  if (!__validate_BPM(bpm)) throw new Error(\`AxonConstraintError: bpm violates BPM constraint (got \${JSON.stringify(bpm)})\`);
  if (!__validate_Duration(duration)) throw new Error(\`AxonConstraintError: duration violates Duration constraint (got \${JSON.stringify(duration)})\`);
  return ({ id, title, artist, bpm, duration, genre, featured: false });
};

/**
 * Format a volume level string — Volume must be 0-100 or auto-guard throws
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Volume} vol
 * @returns {string}
 */
const set_volume = (vol) => {
  if (!__validate_Volume(vol)) throw new Error(\`AxonConstraintError: vol violates Volume constraint (got \${JSON.stringify(vol)})\`);
  return \`Volume set to \${vol}%\`;
};

/**
 * Return the first validation error for new track fields, or empty string if valid
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} title
 * @param {string} artist
 * @param {number} bpm
 * @param {number} duration
 * @returns {string}
 */
const validate_track_input = (title, artist, bpm, duration) => title.length === 0 ? "Title cannot be empty" : artist.length === 0 ? "Artist cannot be empty" : bpm < 60 ? "BPM too low (minimum is 60)" : bpm > 200 ? "BPM too high (maximum is 200)" : duration <= 0 ? "Duration must be greater than 0" : "";

/**
 * Classify BPM range as a human-readable tempo label
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} bpm
 * @returns {string}
 */
const tempo_label = (bpm) => ((_m) => (_m < 90) ? "Slow" : (_m < 120) ? "Moderate" : (_m < 150) ? "Fast" : "Intense")(bpm);

/**
 * Map genre identifier to its accent color CSS class
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} genre
 * @returns {string}
 */
const genre_css_class = (genre) => ((_m) => (_m === "synthwave") ? "g-sw" : (_m === "darksynth") ? "g-ds" : (_m === "ambient") ? "g-amb" : (_m === "retrowave") ? "g-rw" : (_m === "cyberpunk") ? "g-cp" : "g-default")(genre);

/**
 * Abbreviated tag for a genre badge
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {string} genre
 * @returns {string}
 */
const genre_short = (genre) => ((_m) => (_m === "synthwave") ? "SW" : (_m === "darksynth") ? "DS" : (_m === "ambient") ? "AMB" : (_m === "retrowave") ? "RW" : (_m === "cyberpunk") ? "CP" : genre)(genre);

/**
 * Aggregate stats across the track collection — memoized, O(1) on repeated calls
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track[]} tracks
 * @returns {LibraryStats}
 */
const library_stats = (() => {
  const __cache = new Map();
  return (tracks) => {
    const __key = JSON.stringify([tracks]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      let total_dur = sum(map(tracks, __x => __x.duration));
      let total_bpm = sum(map(tracks, __x => __x.bpm));
      let n_featured = count(filter(tracks, __x => __x.featured));
      return {
  count: tracks.length,
  totalDuration: total_dur,
  avgBpm: tracks.length > 0 ? Math.round(total_bpm / tracks.length) : 0,
  featuredCount: n_featured
};
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * Classic recursive Fibonacci — @memo turns O(2^n) into O(n) via Map cache
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {number} n
 * @returns {number}
 */
const fibonacci = (() => {
  const __cache = new Map();
  return (n) => {
    const __key = JSON.stringify([n]);
    if (__cache.has(__key)) return __cache.get(__key);
    const __result = (() => {
      return ((_m) => (_m === 0) ? 0 : (_m === 1) ? 1 : fibonacci(n - 1) + fibonacci(n - 2))(n);
    })();
    __cache.set(__key, __result);
    return __result;
  };
})();

/**
 * Return only featured tracks using .featured shorthand
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track[]} tracks
 * @returns {Track[]}
 */
const featured_tracks = (tracks) => filter(tracks, __x => __x.featured);

/**
 * Extract all track titles using .title shorthand
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track[]} tracks
 * @returns {string}
 */
const all_titles = (tracks) => map(tracks, __x => __x.title);

/**
 * Extract all artist names using .artist shorthand
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track[]} tracks
 * @returns {string}
 */
const all_artists = (tracks) => map(tracks, __x => __x.artist);

/**
 * Sum all durations using .duration shorthand
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track[]} tracks
 * @returns {number}
 */
const total_playtime = (tracks) => sum(map(tracks, __x => __x.duration));

/**
 * Filter tracks to a specific genre
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track[]} tracks
 * @param {string} genre
 * @returns {Track[]}
 */
const tracks_in_genre = (tracks, genre) => filter(tracks, t => t.genre === genre);

/**
 * True if the collection has at least one featured track
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track[]} tracks
 * @returns {boolean}
 */
const any_featured = (tracks) => any(tracks, __x => __x.featured);

/**
 * Return the top n tracks by BPM descending
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track[]} tracks
 * @param {number} n
 * @returns {Track[]}
 */
const top_by_bpm = (tracks, n) => {
  let sorted = tracks.slice().sort((a, b) => b.bpm - a.bpm);
  return sorted.slice(0, n);
};

/**
 * Debug-log a track — @pure is a lie, checker will warn
 * @pure — no side effects
 * @total — always returns, never throws
 * @param {Track} track
 * @returns {boolean}
 */
const debug_track = (track) => {
  console.log("debug_track:", track.title);
  return true;
};

/**
 * Create a DOM element, set attributes, and append children
 * @effects dom.create, dom.attrs, dom.children
 * @param {string} tag
 * @param {Object} attrs
 * @param {*} ...children
 * @returns {Element}
 */
const el = (tag, attrs, ...children) => {
  let e = document.createElement(tag);
  Object.entries(attrs).forEach(([k, v]) => {
    if (k === "class") {
      return e.className = v;
    } else if (k === "id") {
      return e.id = v;
    } else if (k === "disabled") {
      return e.disabled = v;
    } else if (k === "value") {
      return e.value = v;
    } else if (k === "placeholder") {
      return e.placeholder = v;
    } else if (k === "type") {
      return e.type = v;
    } else if (k === "for") {
      return e.setAttribute("for", v);
    } else if (k.startsWith("on")) {
      return e.addEventListener(k.slice(2).toLowerCase(), v);
    } else {
      return e.setAttribute(k, String(v));
    }
});
  children.flat().forEach((child) => {
    if (typeof child === "string") {
      return e.appendChild(document.createTextNode(child));
    } else if (child instanceof Node) {
      return e.appendChild(child);
    }
});
  return e;
};

/**
 * Append a child element into a container element directly
 * @effects dom.write
 * @param {Element} container
 * @param {Element} child
 * @returns {void}
 */
const mount_into = (container, child) => container.appendChild(child);

/**
 * Render a single track as a styled card
 * @effects dom.create
 * @param {Track} track
 * @returns {Element}
 */
const render_track_card = (track) => {
  let label = format_track_label(track);
  let dur = format_duration(track.duration);
  let bpmtag = format_bpm_tag(track.bpm);
  let tempo = tempo_label(track.bpm);
  let gclass = genre_css_class(track.genre);
  let gtag = genre_short(track.genre);
  let cardClass = track.featured ? "track-card track-featured" : "track-card";
  return el("div", { class: cardClass }, el("div", { class: "track-main" }, el("div", { class: "track-label" }, label), el("div", { class: "track-badges" }, el("span", { class: "badge genre-badge " + gclass }, gtag), el("span", { class: "badge tempo-badge" }, tempo), el("span", { class: "badge dur-badge" }, dur), el("span", { class: "badge bpm-badge" }, bpmtag))), track.featured ? el("div", { class: "featured-mark" }, "FEATURED") : el("span", {}));
};

/**
 * Render the live library stats and @memo benchmark badge
 * @effects dom.create
 * @param {Track[]} tracks
 * @returns {Element}
 */
const render_stats_bar = (tracks) => {
  let stats = library_stats(tracks);
  let line = format_stats_line(stats);
  let fib35 = fibonacci(35);
  let fibLabel = format_fibonacci_result(35, fib35);
  return el("div", { class: "stats-bar" }, el("span", { class: "stats-text" }, line), el("span", { class: "memo-badge" }, fibLabel + " (@memo)"));
};

/**
 * Render genre filter pills — active genre is highlighted
 * @effects dom.create
 * @param {string} genres
 * @param {string} activeGenre
 * @param {*} onFilter
 * @returns {Element}
 */
const render_genre_filters = (genres, activeGenre, onFilter) => {
  let buttons = map(genres, g => el("button", { class: g === activeGenre ? "filter-btn filter-btn--active" : "filter-btn" }, g === "all" ? "All Tracks" : g));
  genres.forEach((g, i) => {
    let btn = buttons[i];
    btn.addEventListener("click", () => onFilter(g));
});
  return el("div", { class: "filter-row" }, ...buttons);
};

/**
 * Render an add-track form that demonstrates param validation injection
 * @effects dom.write, dom.create, dom.events
 * @param {Element} container
 * @param {*} onAdd
 * @returns {void}
 */
const render_add_form = (container, onAdd) => {
  let titleIn = el("input", { type: "text", class: "form-inp", placeholder: "Title (required)" });
  let artistIn = el("input", { type: "text", class: "form-inp", placeholder: "Artist (required)" });
  let bpmIn = el("input", { type: "number", class: "form-inp", placeholder: "BPM 60-200" });
  let durIn = el("input", { type: "number", class: "form-inp", placeholder: "Duration (seconds)" });
  let genreIn = el("input", { type: "text", class: "form-inp", placeholder: "Genre (optional)" });
  let errEl = el("div", { class: "form-err" });
  let addBtn = el("button", { class: "add-btn" }, "Add Track");
  addBtn.addEventListener("click", () => {
    let title = titleIn.value;
    let artist = artistIn.value;
    let bpm = parseInt(bpmIn.value);
    let dur = parseInt(durIn.value);
    let genre = genreIn.value.length > 0 ? genreIn.value : "other";
    let err = validate_track_input(title, artist, bpm, dur);
    if (err.length > 0) {
      return errEl.textContent = err;
    } else {
      errEl.textContent = "";
      let newId = Math.floor(Math.random() * 9000) + 1000;
      let track = create_track(newId, title, artist, bpm, dur, genre);
      onAdd(track);
      titleIn.value = "";
      artistIn.value = "";
      bpmIn.value = "";
      durIn.value = "";
      genreIn.value = "";
    }
});
  container.appendChild(el("div", { class: "add-form" }, el("div", { class: "form-header" }, el("h3", { class: "form-title" }, "Add Track"), el("p", { class: "form-note" }, "create_track() has auto-injected guards for BPM (60-200), Duration (> 0), " + "TrackTitle and ArtistName (non-empty). See the transpiled JS tab.")), el("div", { class: "form-fields" }, el("div", { class: "form-row" }, titleIn, artistIn), el("div", { class: "form-row" }, bpmIn, durIn, genreIn)), errEl, addBtn));
};

/**
 * Bootstrap and mount the full music library UI into a root container
 * @effects dom.write, dom.events, state.mutable
 * @param {string} rootId
 * @param {*} initialTracks
 * @returns {void}
 */
const render_library = (rootId, initialTracks) => {
  let tracks = initialTracks.slice();
  let activeGenre = "all";
  let genres = ["all", "synthwave", "darksynth", "ambient", "retrowave", "cyberpunk"];
  let root = document.getElementById(rootId);
  root.innerHTML = "";
  let statsEl = el("div", { class: "stats-section" });
  let filtersEl = el("div", { class: "filters-section" });
  let listEl = el("div", { class: "track-list" });
  let formEl = el("div", { class: "form-section" });
  root.appendChild(statsEl);
  root.appendChild(filtersEl);
  root.appendChild(listEl);
  root.appendChild(formEl);
  let refresh = () => {
    statsEl.innerHTML = "";
    statsEl.appendChild(render_stats_bar(tracks));
    filtersEl.innerHTML = "";
    filtersEl.appendChild(render_genre_filters(genres, activeGenre, (genre) => {
      activeGenre = genre;
      return refresh();
}));
    listEl.innerHTML = "";
    let visible = activeGenre === "all" ? tracks : tracks_in_genre(tracks, activeGenre);
    visible.forEach(t => listEl.appendChild(render_track_card(t)));
};
  render_add_form(formEl, (track) => {
    tracks = [...tracks, track];
    return refresh();
});
  return refresh();
};

`,
};
