// Reads the three source files and writes demo/sources.js with content embedded.
// Run after transpiling: node tools/embed_sources.js
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')

const axn = fs.readFileSync(path.join(root, 'examples', 'controls.syn'), 'utf8')
const ts  = fs.readFileSync(path.join(root, 'examples', 'controls.ts'),  'utf8')
const js  = fs.readFileSync(path.join(root, 'demo',     'controls.synth.js'), 'utf8')

const escape = s => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')

const out = `// Auto-generated by tools/embed_sources.js — do not edit manually
window.SYNTH_SOURCES = {
  axn: \`${escape(axn)}\`,
  ts:  \`${escape(ts)}\`,
  js:  \`${escape(js)}\`,
};
`

fs.writeFileSync(path.join(root, 'demo', 'sources.js'), out, 'utf8')
console.log('✓ Wrote demo/sources.js')
