// Embeds music.axn source and transpiled JS into demo/music.sources.js
// Run after transpiling: node tools/embed_music.js
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')

const axn = fs.readFileSync(path.join(root, 'examples', 'music.axn'), 'utf8')
const js  = fs.readFileSync(path.join(root, 'demo',     'music.axon.js'), 'utf8')

const escape = s => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')

const out = `// Auto-generated by tools/embed_music.js — do not edit manually
window.MUSIC_SOURCES = {
  axn: \`${escape(axn)}\`,
  js:  \`${escape(js)}\`,
};
`

fs.writeFileSync(path.join(root, 'demo', 'music.sources.js'), out, 'utf8')
console.log('✓ Wrote demo/music.sources.js')
